HcityAssets/Controllers/TransactionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using HcityAssets.Models;
using Microsoft.AspNet.Identity;
using Newtonsoft.Json;

namespace HcityAssets.Controllers
{
    [Authorize]
    public class TransactionsController : Controller
    {
        private HCityEntities db = new HCityEntities();

        // GET: Transactions
        public ActionResult Index(string date_from,string date_to,int fee_id=-1)
        {
            var transactions = db.transactions.Include(t => t.fee).Include(t => t.user).Include(t => t.user1);
            if(!string.IsNullOrEmpty(date_from))
            {
                var date_from_ = DateTime.Parse(date_from);
                transactions = transactions.Where(i => i.PaymentDate >= date_from_);
            }
            if (!string.IsNullOrEmpty(date_to))
            {
                var date_to_ = DateTime.Parse(date_to);
                transactions = transactions.Where(i => i.PaymentDate <= date_to_);
            }
            if(fee_id!=-1)
            {
                transactions = transactions.Where(i => i.FeesId == fee_id);
            }
            ViewBag.date_from = date_from;
            ViewBag.date_to = date_to;
            ViewBag.fees = db.fees.ToList();
            ViewBag.fee_id = fee_id;
            
            var payments = transactions.OrderByDescending(i=>i.PaymentDate).ToList();
            return View(payments);
        }

        // GET: Transactions/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            transaction transaction = db.transactions.Find(id);
            var asset = db.assets.Find(transaction.AssetId);
            var company = db.companies.Find(asset.CompanyId);
            if (transaction == null)
            {
                return HttpNotFound();
            }
            ViewBag.payment = transaction;
            ViewBag.company = company;
            return View();
        }

        // GET: Transactions/Create
        public ActionResult Create()
        {
            ViewBag.Assets = db.assets.Where(a => a.user.Id == 1).ToList();
            ViewBag.FeesId = new SelectList(db.fees, "Id", "Title");
            ViewBag.UserId = new SelectList(db.users, "Id", "Firstname");
            return View();
        }

        // POST: Transactions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(transaction transaction, HttpPostedFileBase file , int[] Assets , string[] AssetAmount)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    if (file.ContentLength > 0)
                    {
                         string filetype = Path.GetFileName(file.ContentType);
                        string _FileName = DateTime.Now.ToString("ddMMyyyy") + "-" + transaction.UserId + "-" + transaction.FeesId + "-" + transaction.Amount + "-" + transaction.PaymentMethod + "-" + "."+ filetype;
                        string _path = Path.Combine(Server.MapPath("~/UploadedFiles"), _FileName);
                        file.SaveAs(_path);
                        transaction.Filename = _FileName;
                    }
                    
                    ViewBag.Message = "File Uploaded Successfully!!";
                  //  return View();
                }
                catch ( Exception ex)
                {
                    ViewBag.Message = "File upload failed!!";
                  //  return View();
                }

                db.transactions.Add(transaction);
                db.SaveChanges();

                //Reduce Company balance
                transaction.user = db.users.Find(transaction.UserId);
                var company = db.companies.Find(transaction.user.CompanyId);
                db.Entry(company).State = EntityState.Modified;
                db.SaveChanges();

                //reduce assets balances
                var i = 0;
                foreach (var item in Assets)
                {
                    var asset = db.assets.Find(item);
                    asset.Balance = asset.Balance - Convert.ToDecimal(AssetAmount[i]);
                    db.Entry(asset).State = EntityState.Modified;
                    db.SaveChanges();
                    i++;
                }
                
                //Save assetpayments
                 i = 0;
                var assetpayment = new assetpayment();
                foreach (var item in Assets)
                {
                    assetpayment = new assetpayment { TransactionId= transaction.Id , AssetId = item , Amount = Convert.ToDecimal(AssetAmount[i]),  PaymentMethod = transaction.PaymentMethod , IsPayment = true , UserId= transaction.UserId , FeesId = transaction.FeesId };
                    db.assetpayments.Add(assetpayment);
                    db.SaveChanges();
                    i++;
                }
                
                return RedirectToAction("Index");
            }
            ViewBag.Assets = db.assets.Where(a => a.user.Id == 1).ToList();
            ViewBag.FeesId = new SelectList(db.fees, "Id", "Title", transaction.FeesId);
            ViewBag.UserId = new SelectList(db.users, "Id", "Firstname", transaction.UserId);
            return View(transaction);
        }

        // GET: Transactions/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            transaction transaction = db.transactions.Find(id);
            if (transaction == null)
            {
                return HttpNotFound();
            }
            ViewBag.Assets = db.assets.Where(a => a.user.Id == 1).ToList();
            ViewBag.FeesId = new SelectList(db.fees, "Id", "Title", transaction.FeesId);
            ViewBag.UserId = new SelectList(db.users, "Id", "Firstname", transaction.UserId);
            return View(transaction);
        }

        // POST: Transactions/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(transaction transaction)
        {
            if (ModelState.IsValid)
            {
                db.Entry(transaction).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Assets = db.assets.Where(a => a.user.Id == 1).ToList();
            ViewBag.FeesId = new SelectList(db.fees, "Id", "Title", transaction.FeesId);
            ViewBag.UserId = new SelectList(db.users, "Id", "Firstname", transaction.UserId);
            return View(transaction);
        }


       

        // POST: Transactions/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        private ActionResult Approve_([Bind(Include = "Id,PaymentDate,UserId,FeesId,AssetId,Amount,PaymentMethod,PaymentType,IsApproved,ApprovedDate,ApprovedByUserId")] transaction transaction)
        {
            if (ModelState.IsValid)
            {
                if (transaction.IsApproved)
                {
                    string currentUserId = User.Identity.GetUserId();
                    var currentUser = db.users.Where(a => a.IdentityUserId == currentUserId).FirstOrDefault();
                    transaction.ApprovedByUserId = currentUser.Id;
                    transaction.ApprovedDate = DateTime.Now;
                    transaction.IsPayment = true;

                    db.Entry(transaction).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            ViewBag.Assets = db.assets.Where(a => a.user.Id == 1).ToList();
            ViewBag.FeesId = new SelectList(db.fees, "Id", "Title", transaction.FeesId);
            ViewBag.UserId = new SelectList(db.users, "Id", "Firstname", transaction.UserId);
            ViewBag.ApprovedByUserId = new SelectList(db.users, "Id", "Firstname", transaction.ApprovedByUserId);
            return View(transaction);
        }

        // GET: Transactions/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            transaction transaction = db.transactions.Find(id);
            if (transaction == null)
            {
                return HttpNotFound();
            }
            return View(transaction);
        }

        // POST: Transactions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            transaction transaction = db.transactions.Find(id);
            db.transactions.Remove(transaction);
            db.SaveChanges();
            return RedirectToAction("Index");
        }


        [Route("Approve/{id}")]
        public ActionResult Approve(int id)
        {
            //approve the transaction

            var payment = db.transactions.Where(i => i.Id == id).FirstOrDefault();

HcityAssets/Views/Transactions/Approve.cshtml
@model HcityAssets.Models.transaction
@{
    ViewBag.Title = "Approve";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Transaction</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    <div class="form-group">
        @Html.LabelFor(model => model.PaymentDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.PaymentDate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PaymentDate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.UserId, "UserId", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("UserId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.FeesId, "FeesId", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("FeesId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.FeesId, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PaymentMethod, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.PaymentMethod, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PaymentMethod, "", new { @class = "text-danger" })
        </div>
    </div>

    @*<div class="form-group">
        @Html.LabelFor(model => model.IsPayment, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.IsPayment)
                @Html.ValidationMessageFor(model => model.IsPayment, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>*@
    <div class="form-group">
        @Html.LabelFor(model => model.IsApproved, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.CheckBoxFor(model => model.IsApproved)
                @Html.ValidationMessageFor(model => model.IsApproved, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
  
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HcityAssets/Views/Transactions/Create.cshtml
@model HcityAssets.Models.transaction

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Transactions", FormMethod.Post, new { enctype = "multipart/form-data" } ))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Transaction</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        <label class="control-label col-md-2">User</label>
        <div class="col-md-10">
            @Html.DropDownList("UserId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2">Fees</label>
        <div class="col-md-10">
            @Html.DropDownList("FeesId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.FeesId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2">Asset</label>
        <div class="col-md-10">


            @foreach (var item in ViewBag.Assets)
            {
                if (item.lease != null)
                {
                    <input name="AssetAmount" type="number" value=" @item.Lease.leasetype.Amount" />
                }
                else
                {
                    <input name="AssetAmount" type="number" value="" />
                }
                <input name="Assets" type="checkbox" value="@item.Id" /> @item.Title

                <br> <br>
            }

        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2">Payment method </label>
        <div class="col-md-10">
          @Html.DropDownListFor(m => m.PaymentMethod,
                    new SelectList(Enum.GetValues(typeof(HcityAssets.Models.PaymentMethod))),
                    "Payment Method")
            @Html.ValidationMessageFor(model => model.PaymentMethod, "", new { @class = "text-danger" })
        </div>
    </div>

    @*<div class="form-group">
        <label class="control-label col-md-2">Payment type </label>
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.PaymentType)
                @Html.ValidationMessageFor(model => model.PaymentType, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>*@

    <div>
        @Html.TextBox("file", "", new { type = "file" }) <br />

        @ViewBag.Message

    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-default" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HcityAssets/Views/Transactions/Delete.cshtml
@model HcityAssets.Models.transaction

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3 class="alert alert-danger">Are you sure you want to delete this?</h3>
<div>
    <h4>Transaction</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PaymentDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PaymentDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Amount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Amount)
        </dd>

        <dt>
            Payment Method
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PaymentMethod)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsPayment)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsPayment)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fee.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fee.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.User.Firstname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.Firstname)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> 
            <p style="margin-top:30px;">
                @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-default" })
            </p>
           
        </div>
    }
</div>

HcityAssets/Views/Transactions/Details.cshtml
@{
    var payment = (HcityAssets.Models.transaction)ViewBag.payment;
}

@using HcityAssets.Models;
@using System.Linq;

<style>
    .table-danger
    {
        background-color:red!important;
        color:white!important;
    }
    .table-success{
        background-color:green!important;
        color:white!important;
    }
</style>
<br />
<br />
<br />
<div class="container">
    <div class="row">

        <div class="col-md-6">
            <table style="width:100%" class="table table-striped">

                <tr>
                    <td>
                        Date:
                    </td>
                    <td>
                        @(payment.PaymentDate?.ToString("yyyy-MM-dd"))
                    </td>
                </tr>

                <tr>
                    <td>Company:</td>
                    <td title="">@ViewBag.company.Name</td>
                </tr>

                <tr>
                    <td>
                        Payment For:
                    </td>
                    <td>
                        @payment.fee.Title <span style="color:red;">|</span> @(Globals.get_asset_name(payment.AssetId))
                    </td>
                </tr>



                <tr>
                    <td>
                        Amount:
                    </td>
                    <td>
                        @payment.Amount
                    </td>
                </tr>


                @if (payment.IsApproved)
                {
                    <tr class="table-success">
                        <td>
                            Approved:
                        </td>
                        <td>
                            @(payment.IsApproved ? "Yes" : "No") <span style="color:red;">|</span>  @(payment.ApprovedDate?.ToString("yyyy-MM-dd"))
                        </td>
                    </tr>

                }

                @if (payment.isRejected)
                {
                    <tr class="table-danger">
                        <td>
                            Rejected:
                        </td>
                        <td>
                            @(payment.isRejected ? "Yes" : "No") <span style="color:red;">|</span>  @(payment.ApprovedDate?.ToString("yyyy-MM-dd"))
                        </td>
                    </tr>
                }

                <tr>
                    <td>Action</td>
                    <td>
                        <a href="/Transactions/Approve/@payment.Id" class="label label-success">
                            Accept
                        </a>  &nbsp;|&nbsp;
                        <a href="/Transactions/Reject/@payment.Id" class="label label-danger">
                            Reject
                        </a>
                    </td>
                </tr>

            </table>
            <small style="color:purple">if payment is topup, when you approve the asset will be topped up automatically</small>



        </div>

        <div class="col-md-6">
            <iframe style="width:100%; min-height:600px;" frameborder="0"
                    src="@($"{Globals.client_base_address}Billing/ResourceViewer/{payment.Id}")"
                    allowfullscreen
                    webkitallowfullscreen>
            </iframe>
        </div>

    </div>
</div>

HcityAssets/Views/Transactions/Edit.cshtml
@model HcityAssets.Models.transaction

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Transaction</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.PaymentDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PaymentDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PaymentDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserId, "UserId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("UserId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FeesId, "FeesId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("FeesId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.FeesId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PaymentMethod, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PaymentMethod, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PaymentMethod, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsPayment, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.CheckBoxFor(model => model.IsPayment)
                    @Html.ValidationMessageFor(model => model.IsPayment, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HcityAssets/Views/Transactions/Index.cshtml
@model IEnumerable<HcityAssets.Models.transaction>

@{
    ViewBag.Title = "Index";
}
@using HcityAssets.Models;
<style>
    @*style the drop down select entries - datatables*@
    .custom-select
    {
        height:30px!important;
        width:150px!important;
        margin-left:5px!important;
    }
    @*style the copy buttons- datatables*@
    .dt-buttons
    {
        margin-left:4px!important;
    }
    .table-danger
    {
        background-color:red!important;
        color:white!important;
    }
    .table-success{
        background-color:green!important;
        color:white!important;
    }
</style>



<form method="get" action="/Transactions">
    <table>
        <tr>
            <td>From: </td>
            <td><input type="text" class="form-control" name="date_from" id="date_from" style="padding-left:10px;" value="@ViewBag.date_from"></td>
            <td>To: </td>
            <td><input type="text" class="form-control" name="date_to" id="date_to" style="padding-left:10px;" value="@ViewBag.date_to"></td>
            <td>
            <select name="fee_id" class="form-control" style="margin-left:7px;">
                <option value="-1">All</option>
                @foreach(var item in (List<HcityAssets.Models.fee>)ViewBag.fees)
                {
                    <option value="@item.Id" selected="@((int)ViewBag.fee_id==item.Id)">@item.Title</option>
                }
            </select>
            <td>
               &nbsp; <button type="submit" class="btn btn-primary btn-sm">Filter</button>
            </td>
        </tr>
    </table>
</form>

<br />

<div class="panel panel-primary">
    <div class="panel-heading">Transactions</div>
    <div class="panel-body">

        <table class="table table-sm table-dark" id="dt">
            <thead>
                <tr>
                    <th>
                        Payment date
                    </th>
                    <th>
                        Approved
                    </th>
                    <th>
                        Rejected
                    </th>
                    <th>
                        Amount
                    </th>
                    <th>
                        Fee
                    </th>
                    <th>
                        Company Name
                    </th>

                    <th>
                        Action
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr class="@(item.isRejected?"table-danger":"")@(item.IsApproved?"table-success":"")">
                        <td title="@(item.PaymentDate?.ToString("yyyy-MM-dd"))">
                            @(item.PaymentDate?.ToString("yyyy-MM-dd"))
                        </td>
                        <td>
                            @(item.IsApproved ? "Yes" : "No")
                        </td>
                        <td>
                            @(item.isRejected ? "Yes" : "No")
                        </td>
                        <td>
                            @item.Amount
                        </td>
                        <td>
                            @item.fee.Title
                        </td>
                        <td>
                            <a href="/Companies/Details/@(Globals.get_company_id_from_email(item.ClientEmail))" style="color:black;">
                                <u>@(Globals.get_company_name_from_email(item.ClientEmail))</u>
                            </a>
                        </td>
                        <td>
                            <a href="/Transactions/Details/@item.Id" class="label label-info">
                                View Details
                            </a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>

    </div>
    <div class="panel-footer"></div>
</div>

<script>
    $("#date_from").Zebra_DatePicker({
        format: 'Y-m-d',
        icon_position: 'left'
    });

    $("#date_to").Zebra_DatePicker({
        format: 'Y-m-d',
        icon_position: 'left'
    });

    $('#dt').DataTable({
        responsive: true,
    });

</script>